language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab3_4-stack_queue
  - make -j
  - cd ./bin/
  - ./test/ --gtest_list_tests
notifications:
  email: false
